"""empty message

Revision ID: 27c909d53947
Revises: None
Create Date: 2015-04-08 20:36:09.921213

"""

# revision identifiers, used by Alembic.
revision = '27c909d53947'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewalk_elevation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sidewalk_objectid', sa.Integer(), nullable=True),
    sa.Column('geom', sa.String(length=16), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sidewalk_objectid', sa.Integer(), nullable=True),
    sa.Column('geom', sa.String(length=16), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curb')
    op.drop_table('sidewalk_elevation')
    ### end Alembic commands ###
