"""empty message

Revision ID: 33680eea2e81
Revises: 3a32af97569c
Create Date: 2015-04-11 15:21:54.117655

"""

# revision identifiers, used by Alembic.
revision = '33680eea2e81'
down_revision = '3a32af97569c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curb', 'geom',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('sidewalk_elevation', 'geom',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=1024),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sidewalk_elevation', 'geom',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('curb', 'geom',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    ### end Alembic commands ###
