"""empty message

Revision ID: 37785313b1eb
Revises: 411e0ea55c07
Create Date: 2015-04-28 17:52:46.271973

"""

# revision identifiers, used by Alembic.
revision = '37785313b1eb'
down_revision = '411e0ea55c07'

from alembic import op
import sqlalchemy as sa
import geoalchemy


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy.geometry.Point(), nullable=True),
    sa.Column('objectid', sa.Integer(), nullable=True),
    sa.Column('permit_no', sa.Integer(), nullable=True),
    sa.Column('mobility_impact_text', sa.String(length=2048), nullable=True),
    sa.Column('permit_address_text', sa.String(length=2048), nullable=True),
    sa.Column('applicant_name', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permit')
    ### end Alembic commands ###
