"""empty message

Revision ID: 3a32af97569c
Revises: 27c909d53947
Create Date: 2015-04-11 15:14:30.801112

"""

# revision identifiers, used by Alembic.
revision = '3a32af97569c'
down_revision = '27c909d53947'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
