"""empty message

Revision ID: 3df24d530fcc
Revises: None
Create Date: 2015-07-13 14:37:43.191477

"""

# revision identifiers, used by Alembic.
revision = '3df24d530fcc'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('sidewalk_objectid', sa.Integer(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sidewalk_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.Column('sidewalk_objectid', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('objectid', sa.Integer(), nullable=True),
    sa.Column('permit_no', sa.Integer(), nullable=True),
    sa.Column('mobility_impact_text', sa.String(length=2048), nullable=True),
    sa.Column('permit_address_text', sa.String(length=2048), nullable=True),
    sa.Column('applicant_name', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permit')
    op.drop_table('sidewalk_grade')
    op.drop_table('curb')
    ### end Alembic commands ###
