"""empty message

Revision ID: 411e0ea55c07
Revises: None
Create Date: 2015-04-20 14:14:55.853461

"""

# revision identifiers, used by Alembic.
revision = '411e0ea55c07'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewalk_elevation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sidewalk_objectid', sa.Integer(), nullable=True),
    sa.Column('coordinates', geoalchemy.geometry.LineString(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sidewalk_objectid', sa.Integer(), nullable=True),
    sa.Column('coordinates', geoalchemy.geometry.Point(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curb')
    op.drop_table('sidewalk_elevation')
    ### end Alembic commands ###
