"""empty message

Revision ID: e3622c9a36b
Revises: 27c909d53947
Create Date: 2015-04-10 18:32:02.680727

"""

# revision identifiers, used by Alembic.
revision = 'e3622c9a36b'
down_revision = '27c909d53947'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
